In [1]:
import numpy as np


In [2]:
myarr =np.array([3,5,7,88,99])


In [3]:
myarr

array([ 3,  5,  7, 88, 99])

In [4]:
print(myarr)

[ 3  5  7 88 99]


In [5]:
myarr[3]

88

In [6]:
arr1=np.array(([3,11,34,6,8,9,7],[67,90,8,3,7,9,1]))

In [7]:
arr1

array([[ 3, 11, 34,  6,  8,  9,  7],
       [67, 90,  8,  3,  7,  9,  1]])

In [8]:
arr1[0,2]

34

In [9]:
arr1[1,1]

90

In [10]:
#specific row
arr1[0, :]

array([ 3, 11, 34,  6,  8,  9,  7])

In [11]:
#specific col
arr1[:,1]

array([11, 90])

In [12]:
# [start index:end index:step size]
arr1[0,1:6:2]

array([11,  6,  9])

In [13]:
arr1.shape

(2, 7)

In [14]:
arr1.dtype

dtype('int32')

In [15]:
arr1[0,2]=1

In [16]:
arr1

array([[ 3, 11,  1,  6,  8,  9,  7],
       [67, 90,  8,  3,  7,  9,  1]])

In [17]:
arr2=np.array((([3,4,2.3],[4,7,0],[1.1,8.9,0])))

In [18]:
arr2

array([[3. , 4. , 2.3],
       [4. , 7. , 0. ],
       [1.1, 8.9, 0. ]])

In [19]:
arr2.dtype

dtype('float64')

# some functions of array creation

**1. zeros**

In [20]:
zeros=np.zeros((2,4))

In [21]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
#ones
ones=np.ones((2,4))

In [23]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
zeros.dtype

dtype('float64')

In [25]:
zeros.size

8

In [26]:
#full
full=np.full((2,2),55)

In [27]:
full

array([[55, 55],
       [55, 55]])

In [28]:
#random decimal numbers
np.random.rand(4,2)

array([[0.21836918, 0.20963116],
       [0.985297  , 0.21168046],
       [0.03451701, 0.2309956 ],
       [0.80411287, 0.76709599]])

In [29]:
#random integer values
np.random.randint(4,7 , size=(3,3))
# here value shoulb be between 4,7 and size 3*3

array([[4, 4, 4],
       [6, 5, 5],
       [6, 5, 5]])

**2. arange**

In [30]:
arange=np.arange(8)

In [31]:
arange

array([0, 1, 2, 3, 4, 5, 6, 7])

**3.linspace**

In [32]:
linspace=np.linspace(1,5,12)

In [33]:
linspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

gives 12 elements between 1 and 5 which are equally and linearly spaced

In [34]:
linspace1=np.linspace(1,50,10)

In [35]:
linspace1

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

**3.empty**

In [36]:
empty=np.empty((4,5))

In [37]:
empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.45066124e-308, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306],
       [2.22518251e-306, 1.33511969e-306, 1.78022342e-306,
        1.05700345e-307, 3.11525958e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306]])

gives a empty array with random elements.

**4.empty_like**

In [38]:
empty_like=np.empty_like(arr1)

In [39]:
empty_like

array([[          0,  1074266112,           0,  1074790400,  1717986918,
         1073899110,           0],
       [ 1074790400,           0,  1075576832, -1717986918,  1072798105,
         -858993459,  1075956940]])

**5.identity**

In [40]:
identity=np.identity(15)

In [41]:
identity

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

gives an identity matrix of 15*15

In [42]:
identity.size

225

In [43]:
identity.shape

(15, 15)

In [44]:
#REPEAT an array
a=np.array([[1,2,3]])
r1= np.repeat(a,3,axis=0)
print(r1)                             # repeat an array 3 times

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [45]:
output= np.ones((5,5))
print (output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
z=np.zeros((3,3))
z[1,1]=9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [47]:
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**6.reshape**

In [48]:
arr3=np.arange(99)

In [49]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr3.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

reshapes 99 into 3*33 but make sure the real is divisible by the two you want to reshape it by.

In [51]:
arr4=np.arange(45)

In [52]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [53]:
arr4.reshape(9,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

but this wont change the real array. to change it,or to make the reshaped one the real one;


In [54]:
arr4=arr4.reshape(9,5)

In [55]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [56]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [57]:
#horizonatlly stacked vectors
h1=np.zeros((2,3))
h2=np.full((2,3),3)

np.hstack([h1,h2])

array([[0., 0., 0., 3., 3., 3.],
       [0., 0., 0., 3., 3., 3.]])

**5.ravel**

In [58]:
arr4.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

makes it 1d array

**numpy axis**
1D [1,2,3,4] has 1 axis which is axis 0

2D [[1,2,3]
    [4,5,6]
    [7,8,9]] has 2 axis which are axis0 and axis1;; axis0 is rows and axis1 is columns
              like summation of axis0 is [12,15,18] and axis1 is [6.
                                                                  15.
                                                                  24.]

In [59]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [60]:
ar=np.array(x)

In [61]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [62]:
ar.sum(axis=0)

array([12,  8,  9])

In [63]:
ar.sum(axis=1)

array([ 6, 15,  8])

***ATTRIBUTES OF ARRAYS***

In [64]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

transposes, rows to col and vice versa

In [65]:
ar.flat

In [66]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


flat; printss every item


In [67]:
ar.ndim

2

gives dimension of given array

In [68]:
ar.size

9

In [69]:
ar.nbytes

36

total bytes consumes

In [70]:
one=np.array([1,2,3,77,987,0])

In [71]:
one.argmax()

4

In [72]:
one.argmin()

5

gives the index nos of max and min

In [73]:
one.argsort()

array([5, 0, 1, 2, 3, 4], dtype=int64)

gives index nos of the how the nos would be if they were sorted

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [76]:
ar.argmin()


8

In [77]:
ar.argmax()

6

In [78]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [79]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [80]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [81]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

***mathematical operations in numpy***

In [82]:
ar1=np.array(([1,2,5],[7,5,6],[2,5,1]))

In [83]:
ar+ar1

array([[ 2,  4,  8],
       [11, 10, 12],
       [ 9,  6,  1]])

In [84]:
ar*ar1

array([[ 1,  4, 15],
       [28, 25, 36],
       [14,  5,  0]])

In [85]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [86]:
ar.sum()

29

In [87]:
ar.max()

7

In [88]:
ar.min()

0

In [89]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [90]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [91]:
np.count_nonzero(ar)

8

***basic maths***

In [92]:
b=np.array([1,2,3,5])
b

array([1, 2, 3, 5])

In [93]:
b+2

array([3, 4, 5, 7])

In [94]:
np.sin(b)

array([ 0.84147098,  0.90929743,  0.14112001, -0.95892427])

***linear algebra***

In [95]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [96]:
b=np.full((3,2),2)
print(b)


[[2 2]
 [2 2]
 [2 2]]


In [97]:
np.matmul(a,b)     #MATMUL FUNCTION.(matriu]x multiplication)

array([[6., 6.],
       [6., 6.]])

In [98]:
#normal operations are not gonna work here as these are of diff sizes, so we have to use other functions for linear algebra
#here, the cols of first matrix should be equal to rows of the second matrix ie 3 and 3 and the resultant matrix will be 2* 2


In [99]:
#FIND THE DETERMINANT
c=np.identity(3)
np.linalg.det(c)        #linalg.det function.

1.0

In [134]:
a.dot(b)

array([[6., 6.],
       [6., 6.]])

In [135]:
a@b

array([[6., 6.],
       [6., 6.]])

In [ ]:
# THERE ARE VARIOUS OTHER ALGEBRIC FUNCTIONS YOU CAN DO WITH MATRIX CHECK GOOGLE.

***STATISTICS***

In [101]:
s=np.array(([6,8,1],[2,3,5]))
s

array([[6, 8, 1],
       [2, 3, 5]])

In [102]:
s.max()


8

In [103]:
s.min()

1

In [104]:
s.sum()

25

***MISCELLANEOUS***

**1. LOAD DATA FROM FILE**

In [105]:
fd=np.genfromtxt("data.txt",delimiter=",")

fd

ValueError: Some errors were detected !
    Line #2 (got 18 columns instead of 24)
    Line #3 (got 16 columns instead of 24)

In [106]:
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [107]:
a1.mean()

2.5

In [109]:
a1.var()

1.25

In [110]:
a1.std()

1.118033988749895

### BROADCASTING AND VECTORISED OPERATIONS

In [112]:
c=np.arange(4)
c

array([0, 1, 2, 3])

In [113]:
c+10


array([10, 11, 12, 13])

In [114]:
c*10

array([ 0, 10, 20, 30])

In [116]:
[i+10 for i in c]

[10, 11, 12, 13]

### BOOLEAN

In [117]:
c=np.arange(4)
c

array([0, 1, 2, 3])

In [121]:
c[[True,False,True,False]]

array([0, 2])

In [122]:
c>=2

array([False, False,  True,  True])

In [123]:
c[c>=2]

array([2, 3])

In [124]:
c.mean()

1.5

In [128]:
c[~(c>c.mean())]

array([0, 1])

In [129]:
c[c>c.mean()]

array([2, 3])

In [130]:
c[(c==1)|(c==2)]

array([1, 2])

In [132]:
c[(c>1)&(c%2==0)]

array([2])

In [133]:
c[(c>2)|(c%2==0)]

array([0, 2, 3])

### SOME OTHERS

In [136]:
np.random.random(size=3)

array([0.42555583, 0.79422433, 0.12594472])

In [137]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [138]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [139]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])